### ISSUE TITLE
No muestra todos los contenidos de la pantalla

### ISSUE THREAD

**Issue by JNylson** [hxebolax/Tienda-para-NVDA#8]
Simplemente muestra la descripción y no puede cambiar el tamaño de la ventana
Windows 10 21h1 64bits
resolución 1280 x 768

![Captura de Tela (15)](https://user-images.githubusercontent.com/20192563/135642374-e7d62673-6618-4a5e-b84b-e82ddaabafd2.png)

**Comment by hxebolax** [comment]
Hola, hace mucho tiempo vengo comentando a NVDA que tiene un problema en la propiedad size en wxpython.

Hasta el día de hoy no e recibido ninguna contestación y yo no puedo hacer nada.


Si la ventana de la tienda la hago en una aplicación externa tiene como propiedad unos 850x550 pero si quiero pasar esa propiedad a NVDA no me queda otra que ponerle 1600x800 siendo exactamente el mismo tamaño en NVDA que en la aplicación externa. Esto comprobado con persona que ve bien.

Entonces no puedo hacer la ventana como en la versión externa ya que nos quedaría todo absolutamente montado.

Siento esta inconveniencia para resoluciones pequeñas pero en mi no está el poder solucionarlo.

Y no voy a hacer ventanas dinámicas pensando en las distintas resoluciones porque me podría volver loco.

Saludos

**Comment by JNylson** [comment]
https://github.com/hxebolax/Tienda-para-NVDA/pull/9
